# 동작 환경 설정
spring:
  profiles:
    active: prod
server:
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    path: /error
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    session:
      timeout: 1440m      # 60m * 24h * 30d
      cookie:
        max-age: 1440m    # 60m * 24h * 30d
        name: SID
        http-only: true
        secure: false
        
# 개발 환경
--- 
logging:
  file.name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.dev.IBIOECommerce: DEBUG
    org.hibernate: ERROR
spring:
  config:
    activate: 
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://119.205.220.240:3306/ibio?useUnicode=true&characterEncoding=utf8
    username: root
    password: ghksrka3849!
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: -1
      enabled : true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'admin@ibioscience.co.kr'
    password: 'vukqdrgkpagrvomf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  upload.path: D:/TestAssets/
  upload.env: local

# 배포 환경
--- 
logging:
  file.name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.dev.BionLifeScienceWar: DEBUG
    org.hibernate: ERROR
spring:
  config:
    activate: 
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ghksrka3849!
    url: jdbc:mariadb://119.205.220.240:3306/ibio?useUnicode=true&characterEncoding=utf8
    username: root
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: -1
      enabled : true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'admin@ibioscience.co.kr'
    password: 'vukqdrgkpagrvomf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  upload.path: /project/files/
  upload.env: prod


